books:
  test:
    page1:
      - "<green>Welcome to the <bold>server!</bold></green>"
      - text: "<blue><underlined>Click here for Paper docs</underlined></blue>"
        url: "https://docs.papermc.io/"
      - "<gray>Another line</gray>"
      - text: "<gold><bold>Server store</bold></gold>"
        url: "https://wayhaven.tebex.io/"
      - text: "You can also hover over this link"
        url: "https://wayhaven.tebex.io/"
        hover: "<gold>This link open server store</gold>"
    page2:
    page3:
      - "Page 3"
  rankbenefits:
    page1:
      - "You can obtain ranks through multiple avenues. 
        Below details all of the current ranks and how to obtain them."
      - ""
      - text: "• <green>Mapmaker</green> Rank"
        hover: "<green>‣ Making imageframes\n‣ Mapmaker prefix in-game</green>\n<gray>Obtainable by becoming a cartographer in the Cartography Guild and making maps consistently.</gray>"
      - text: "• <red>News</red> Rank"
        hover: "<red>‣ Making imageframes\n‣ News prefix in-game</red>\n<gray>Obtainable by becoming a newsperson (Open a ticket on discord and provide an example of what your news might look like!) and posting news consistently.</gray>"
      - text: "• <gold>Gold</gold> Rank"
        hover: "<gold>‣ /stonecutter\n‣ /loom\n‣ /smithingtable\n‣ Making imageframes\n‣ Gold prefix in-game</gold>\n<gray>Obtainable through purchasing on the store or through referring 100 people.</gray>"
      - text: "• <dark_green>Emerald</dark_green> Rank"
        hover: "<dark_green>‣ /stonecutter\n‣ /loom\n‣ /smithingtable\n‣ /hat\n‣ /echest\n‣ Username in supporters' list at spawn\n‣ Making imageframes\n‣ Emerald prefix in-game</dark_green>\n<gray>Obtainable through purchasing on the store</gray>"
      - text: "• <blue>Diamond</blue> Rank"
        hover: "<blue>‣ /stonecutter\n‣ /loom\n‣ /smithingtable\n‣ /hat\n‣ /echest\n‣ /epicrename to change the lore information of items and rename them\n‣ Username in supporters' list at spawn\n‣ Making imageframes\n‣ Diamond prefix in-game</blue>\n<gray>Obtainable through purchasing on the store</gray>"
      - text: "• <color:#4B3B6B>Netherite</color> Rank"
        hover: "<color:#4B3B6B>‣ /stonecutter\n‣ /loom\n‣ /smithingtable\n‣ /hat\n‣ /echest\n‣ /epicrename to change the lore information of items and rename them\n‣ /trash\n‣ /condense\n‣ Username in supporters' list at spawn\n‣ Making imageframes\n‣ Netherite prefix in-game</color>\n<gray>Obtainable through purchasing on the store</gray>"
