book:
  page1:
    - "<green>Welcome to the <bold>server!</bold></green>"
    - text: "<blue><underlined>Click here for Paper docs</underlined></blue>"
      url: "https://docs.papermc.io/"
    - "<gray>Another line</gray>"
    - text: "<gold><bold>Server store</bold></gold>"
      url: "https://wayhaven.tebex.io/"
    - text: "You can also hover over this link"
      url: "https://wayhaven.tebex.io/"
      hover: "<gold>This link open server store</gold>"
  page2:
  page3:
    - "Page 3"